platform :ios,'9.0'

# fix Generated duplicate UUIDs
install! 'cocoapods',
         :deterministic_uuids => false

target 'RNAmapKitExample' do
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    ]

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'react-native-amap-kit', path: '../node_modules/react-native-amap-kit/ios'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
  # fix conflict
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end

  installer.pods_project.targets.each do |target|
    if target.name == 'Pods-RNAmapKitExample'
      target.build_configurations.each do |config|
        # fix amap
        xcconfig_path = config.base_configuration_reference.real_path
        build_settings = Hash[*File.read(xcconfig_path).lines.map{|x| x.split(/\s*=\s*/, 2)}.flatten]
        build_settings['OTHER_LDFLAGS'][' -l"stdc++.6.0.9"'] = ''
        File.open(xcconfig_path, "w") do |file|
          build_settings.each do |key,value|
            file.puts "#{key} = #{value}"
          end
        end
      end
    end
  end
end
