platform :ios,'9.0'

# fix Generated duplicate UUIDs
install! 'cocoapods',
         :deterministic_uuids => false

target 'RNAmapKitExample' do
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTImage',
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    ]

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'react-native-amap-kit', path: '../node_modules/react-native-amap-kit'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

post_install do |installer|
  # fix conflict
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end

    if target.name == "yoga"
      target.remove_from_project
    end
  end
end
